---
name: CAM-SOAPApp
version: 1.06
author:
  - 'Clotho Advanced Media Inc., I<cpan@clotho.com>'
abstract: SOAP application framework
license: perl
resources:
  license: perl://dev.perl.org/licenses/
requires:
  CAM::App: 0.08
  SOAP::Lite: 0.55
  perl: 5.6.0
build_requires:
  HTTP::Daemon: 1.00
  IO::Socket: 1.00
  Test::More: 0.01
recommends:
  LWP::UserAgent: 2.00
provides:
  CAM::SOAPApp:
    file: lib/CAM/SOAPApp.pm
    version: 1.06
generated_by: Module::Build version 0.2706
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
